apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: health-check-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: health-check-service
    spec:
      containers:
        - name: health-check-service
          image: quay.io/zotovsa/healthcheckservic
          imagePullSecrets:
            - name: regsecret
          ports:
            - containerPort: 8080
              name: http