apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greetings-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: greetings-service
    spec:
      containers:
        - name: greetings-service
          image: quay.io/zotovsa/greetings-service
          ports:
            - containerPort: 8080
              name: http
