apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "health-check-service"
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: health-check-service
          servicePort: 8080
